#!/bin/bash
sudo apt-get -y -f install gnupg2 make
mkdir -p gpg
chmod 700 gpg
cat - <<EOF | gpg2 --batch --gen-key --homedir gpg
%echo Generating a basic OpenPGP key
%no-ask-passphrase
Key-Type: RSA
Key-Length: 2048
Subkey-Type: RSA
Subkey-Length: 2048
Name-Real: gpg
Name-Comment: Generated by $0 gpg
Name-Email: gpg
Expire-Date: 0
# Do a commit here, so that we can later print "done" :-)
%commit
%echo Done
EOF
gpg2 --homedir gpg --output apt-key.gpg --armor --export gpg
gpg2 --homedir gpg --output gpg/gpg_key.gpg --armor --export-secret-key gpg
